CREATE TABLE MEMBER (
           ID VARCHAR2(20) PRIMARY KEY,
          PWD VARCHAR2(20) NOT NULL,
         NAME VARCHAR2(20) NOT NULL,
       GENDER CHAR(1),
     BIRTHDAY CHAR(6),
        EMAIL VARCHAR2(30),
      ZIPCODE CHAR(5),
      ADDRESS VARCHAR2(100),
DETAILADDRESS VARCHAR2(50),
        HOBBY CHAR(5),
          JOB VARCHAR2(30)
);