CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(20),
    USE_YN CHAR(1) DEFAULT 'Y'
);

CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(20)
);

CREATE TABLE TB_국어국문학과3(학번, 학생이름, 출생년도, 교수이름)
AS SELECT STUDENT_NO, STUDENT_NAME, SUBSTR(TO_DATE(SUBSTR(STUDENT_SSN,1,2),'RRRR'),1,4) 출생년도 , PROFESSOR_NAME
--        , EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,2),'RRRR')) 출생년도
        
     FROM TB_STUDENT S
     LEFT JOIN TB_PROFESSOR ON (PROFESSOR_NO = S.COACH_PROFESSOR_NO)
     LEFT JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
    WHERE DEPARTMENT_NAME = '국어국문학과';
    

UPDATE TB_STUDENT
   SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);
   
--SELECT SUBSTR(STUDENT_SSN,1,8)||'******' AS "주민번호 뒷자리생략"
--FROM TB_STUDENT;

SELECT STUDENT_NAME, DEPARTMENT_NAME, POINT, TERM_NO, CLASS_NAME
  FROM TB_STUDENT
  JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
  JOIN TB_GRADE USING(STUDENT_NO)
  JOIN TB_CLASS USING(CLASS_NO)
 WHERE STUDENT_NAME = '김명훈'
   AND DEPARTMENT_NAME = '의학과'
   AND TERM_NO = '200501'
   AND CLASS_NAME = '피부생리학';
   
UPDATE TB_GRADE
   SET POINT = 3.5
 WHERE STUDENT_NO = (SELECT STUDENT_NO
                       FROM TB_STUDENT
                       JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                      WHERE STUDENT_NAME = '김명훈'
                        AND DEPARTMENT_NAME = '의학과')
   AND TERM_NO = '200501'              
   AND CLASS_NO = (SELECT CLASS_NO
                       FROM TB_CLASS
                      WHERE CLASS_NAME = '피부생리학');

DELETE FROM TB_GRADE
 WHERE STUDENT_NO IN (SELECT STUDENT_NO
                        FROM TB_STUDENT
                       WHERE ABSENCE_YN = 'Y');


